name: bmi_calculator
description: A BMI Calculator app with login and signup.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.0.9
  swipeable_button_view: ^0.0.2
  flutter_3d_choice_chip: ^0.1.4
  pretty_gauge: ^1.0.0
  share_plus: ^11.0.0
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.19.0   # <-- Add this line
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg